
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plato-system
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
